export const TOGGLE_TEST = 'TOGGLE_TEST';
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';


export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const PUT_VOTECOMMENTS_REQUEST = 'PUT_VOTECOMMENTS_REQUEST';
export const PUT_VOTECOMMENTS_SUCCESS = 'PUT_VOTECOMMENTS_SUCCESS';
export const PUT_VOTECOMMENTS_FAILURE = 'PUT_VOTECOMMENTS_FAILURE';